"""
Logging configuration module for the application.
Sets up a unified logger that outputs to both the console and daily rotating files.
Logs are stored in the 'logs/' directory with a 'YYYYMMDD.log' naming convention.
"""

import logging
import os
from datetime import datetime
from logging.handlers import TimedRotatingFileHandler

from app.core.config import Config


def setup_logger():
    """
    Configure and initialize the global application logger.

    The logger is configured with:
    - A TimedRotatingFileHandler for daily file-based logs.
    - A StreamHandler for real-time console output.
    - A standard message format including timestamp and log level.

    Returns:
        logging.Logger: The fully configured logger instance.
    """
    # Ensure the logs directory exists on the filesystem
    log_dir = "logs"
    os.makedirs(log_dir, exist_ok=True)

    # Initial log filename based on the current date
    log_filename = os.path.join(log_dir, f"{datetime.now().strftime('%Y%m%d')}.log")

    # Get a logger instance with the application name
    logger = logging.getLogger(Config.APP_NAME)
    # Set global logging level to INFO (ignores DEBUG messages by default)
    logger.setLevel(logging.INFO)

    # Prevent adding duplicate handlers if the logger is re-initialized
    if not logger.handlers:
        # Define a consistent format for all log entries
        formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")

        # 1. File Handler: Rotates every midnight, keeps logs for 30 days
        handler = TimedRotatingFileHandler(
            log_filename, when="midnight", interval=1, backupCount=30, encoding="utf-8"
        )
        handler.setFormatter(formatter)

        def namer(default_name):
            """
            Custom namer function for rotated log files.
            Converts the default 'app.log.YYYY-MM-DD' suffix to 'YYYYMMDD.log'.

            Args:
                default_name (str): The default filename generated by the handler.

            Returns:
                str: The path to the newly named log file.
            """
            base_dir = os.path.dirname(default_name)
            parts = default_name.split(".")
            rotate_date_str = parts[-1]  # The YYYY-MM-DD part
            try:
                # Reformat the date string for cleaner filenames
                date_obj = datetime.strptime(rotate_date_str, "%Y-%m-%d")
                new_name = date_obj.strftime("%Y%m%d") + ".log"
            except ValueError:
                # If parsing fails, fall back to the original name
                new_name = default_name
            return os.path.join(base_dir, new_name)

        # Attach the custom namer to the handler
        handler.namer = namer
        logger.addHandler(handler)

        # 2. Console Handler: Outputs logs to stdout for container/CLI monitoring
        console_handler = logging.StreamHandler()
        console_handler.setFormatter(formatter)
        logger.addHandler(console_handler)

    return logger


# Instantiate the logger once for use across the entire application
logger = setup_logger()
